/* Wires roms/rom_images.c's ROM page arrays (generated by
 * roms/rom_to_c.py from NUT0-2.ROM - the base HP-41 OS, 3 pages) into
 * nutcpu.h's tabpage[]/typmod[], and resets CPU state to Nut's
 * documented cold-start values.
 */

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom.h"
#include <stdint.h>

/* rom_images.c has no header of its own (rom_to_c.py only emits the .c
 * file) - declared extern here instead. If the ROM set wired in ever
 * changes (e.g. XNUT/CXFUNS/ADV pages for module support later), update
 * this alongside it.
 */
extern const uint16_t rom_nut0[4096];
extern const uint16_t rom_nut1[4096];
extern const uint16_t rom_nut2[4096];

void nut_boot(void)
{
  /* tabpage[] wants `short *`; the ROM arrays are `const uint16_t[]`.
   * Safe to discard const here: typmod[page]==1 (ROM) is never a valid
   * target for wmldl1()'s write path (wmldl() only writes to typ 5/7/9/11
   * pages), so nothing ever writes through these pointers.
   */
  tabpage[0] = (short *)(const void *)rom_nut0;
  tabpage[1] = (short *)(const void *)rom_nut1;
  tabpage[2] = (short *)(const void *)rom_nut2;
  typmod[0] = 1;
  typmod[1] = 1;
  typmod[2] = 1;

  /* Cold-start CPU state. Mirrors the fields emu41gcc's own
   * loader.c:initcpu() sets that actually matter for a fresh boot -
   * everything else it resets there is already zero from BSS, which is
   * exactly what a from-scratch bring-up wants anyway.
   */
  regPC = 0;
  regST = 0x0800;    /* stack lift enabled */
  Carry = 1;         /* coldstart flag - checked by the ROM on power-up */
  mode_printer = -1; /* no HP82143 printer plugged in */
}
