/**
 * @file nut_rom_hpil.c
 * @brief Implementation - see nut_rom_hpil.h for the full contract and
 *        why this is a separate file from nut_rom.c.
 */

#include <assert.h>
#include <stddef.h>
#include <stdint.h>

#define GLOBAL extern
#include "nutcpu.h"

#include "nut_rom_hpil.h"

/* roms/rom_images_hpil.c (generated by roms/mod_to_c.py from
 * roms/HPIL.MOD) has no header of its own, same as rom_images.c -
 * declared extern here instead. Names/pages per roms/HPIL.MOD's own
 * declared metadata (printed by mod_to_c.py's own summary output):
 * "ILPrinter-2E" -> Page 6, "ILModule-1H" -> Page 7. */
extern const uint16_t rom_hpil_p0[4096];
extern const uint16_t rom_hpil_p1[4096];

void nut_rom_wire_hpil_module(void) {
    /* tabpage[] wants `short *`; the ROM arrays are `const uint16_t[]`
     * - same const-discard rationale as nut_rom.c's own nut_boot():
     * typmod[page]==1 (ROM) is never a valid target for wmldl1()'s
     * write path, so nothing ever writes through these pointers. */
    tabpage[6] = (short *)(const void *)rom_hpil_p0;
    tabpage[7] = (short *)(const void *)rom_hpil_p1;
    typmod[6] = 1;
    typmod[7] = 1;
    assert(tabpage[6] != NULL && tabpage[7] != NULL);
    assert(typmod[6] == 1 && typmod[7] == 1);
}
