#!/usr/bin/env python3
"""Convert monochrome mockup PNGs into GDRAM-formatted byte arrays.

144x32 mockups, for use with the NHD-14432WG proof-of-concept sketch.

Packing assumptions (see README / chat notes for confidence level on these):
  - GDRAM is written 16 bits (2 bytes) at a time, MSB first, left pixel = MSB.
  - 144 px wide / 16 = 9 words per row, 32 rows -> 9*2*32 = 576 bytes/image.
  - A black source pixel (dark segment) -> GDRAM bit = 1 (pixel "on").
    This matches the FSTN transflective convention where "on" segments are
    dark, but if the display comes up inverted, flip ON_IS_BLACK below.

Usage (run from this directory, or anywhere - paths below are relative to
this script's own location):
    python3 convert_images.py
Reads mockup PNGs from ../../reference-material/display-mockups/ (see
CLAUDE.md's "Directory map") and writes bitmaps.h alongside this script.
"""
from pathlib import Path

from PIL import Image

SCRIPT_DIR = Path(__file__).resolve().parent
MOCKUP_DIR = SCRIPT_DIR / ".." / ".." / "reference-material" / "display-mockups"
OUTPUT_PATH = SCRIPT_DIR / "bitmaps.h"

ON_IS_BLACK = True
GRAYSCALE_THRESHOLD = 128
WIDTH, HEIGHT = 144, 32
BITS_PER_WORD = 16
WORDS_PER_ROW = WIDTH // BITS_PER_WORD  # 9
BYTES_PER_IMAGE = WORDS_PER_ROW * 2 * HEIGHT  # 576

IMAGES = [
    ("NHD14432_Mockup_00000.png", "bmp_00000"),
    ("NHD14432_Mockup_MemoryLost.png", "bmp_memory_lost"),
    ("NHD14432_Mockup_AllSegments.png", "bmp_all_segments"),
]


def check(condition: bool, message: str) -> None:
    """Power of 10 (Python adaptation), Rule 5 assertion helper.

    Unlike a bare `assert` statement, this is never compiled out under
    `-O`/`-OO` - see ../../DEVIATIONS.md's implementation note on why
    this project uses `check()` instead of `assert` for anything Rule 5
    actually requires.
    """
    if not condition:
        raise AssertionError(message)


def convert(path: Path) -> bytearray:
    """Convert one 144x32 monochrome mockup PNG into packed GDRAM bytes.

    Args:
        path: Path to the source PNG (must be exactly 144x32).

    Returns:
        BYTES_PER_IMAGE (576) bytes, MSB-first per 16-bit word, ready to
        write straight to GDRAM.
    """
    im = Image.open(path).convert("L")
    w, h = im.size
    check((w, h) == (WIDTH, HEIGHT), f"{path} is {w}x{h}, expected {WIDTH}x{HEIGHT}")
    px = im.load()
    out = bytearray()
    for y in range(HEIGHT):
        for word in range(WORDS_PER_ROW):
            val = 0
            for bit in range(BITS_PER_WORD):
                x = word * BITS_PER_WORD + bit
                p = px[x, y]
                is_on = (p < GRAYSCALE_THRESHOLD) if ON_IS_BLACK else (p >= GRAYSCALE_THRESHOLD)
                if is_on:
                    val |= (1 << (BITS_PER_WORD - 1 - bit))
            out.append((val >> 8) & 0xFF)
            out.append(val & 0xFF)
    check(len(out) == BYTES_PER_IMAGE,
          f"{path}: produced {len(out)} bytes, expected {BYTES_PER_IMAGE}")
    return out


def to_progmem_array(name: str, data: bytearray) -> str:
    """Format packed image bytes as a PROGMEM C array declaration.

    Args:
        name: C identifier for the array.
        data: Packed bytes, as produced by convert().

    Returns:
        The full C source text for this array's declaration.
    """
    lines = [f"const uint8_t {name}[{len(data)}] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    """Convert each mockup PNG in IMAGES and write the combined bitmaps.h."""
    header = ["// Auto-generated by convert_images.py — do not hand-edit.",
              "#pragma once",
              "#include <avr/pgmspace.h>",
              ""]
    for fname, varname in IMAGES:
        path = MOCKUP_DIR / fname
        data = convert(path)
        header.append(to_progmem_array(varname, data))
        header.append("")
    with OUTPUT_PATH.open("w") as f:
        f.write("\n".join(header))
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
