#!/usr/bin/env python3
"""
Convert 144x32 monochrome mockup PNGs into byte arrays formatted for the
ST7920's GDRAM, for use with the NHD-14432WG proof-of-concept sketch.

Packing assumptions (see README / chat notes for confidence level on these):
  - GDRAM is written 16 bits (2 bytes) at a time, MSB first, left pixel = MSB.
  - 144 px wide / 16 = 9 words per row, 32 rows -> 9*2*32 = 576 bytes/image.
  - A black source pixel (dark segment) -> GDRAM bit = 1 (pixel "on").
    This matches the FSTN transflective convention where "on" segments are
    dark, but if the display comes up inverted, flip ON_IS_BLACK below.
"""

from PIL import Image
import os

ON_IS_BLACK = True
THRESHOLD = 128
WIDTH, HEIGHT = 144, 32
WORDS_PER_ROW = WIDTH // 16  # 9

SOURCE_DIR = "/mnt/user-data/uploads"
IMAGES = [
    ("NHD14432_Mockup_00000.png", "bmp_00000"),
    ("NHD14432_Mockup_MemoryLost.png", "bmp_memory_lost"),
    ("NHD14432_Mockup_AllSegments.png", "bmp_all_segments"),
]

def convert(path):
    im = Image.open(path).convert("L")
    w, h = im.size
    assert (w, h) == (WIDTH, HEIGHT), f"{path} is {w}x{h}, expected {WIDTH}x{HEIGHT}"
    px = im.load()
    out = bytearray()
    for y in range(HEIGHT):
        for word in range(WORDS_PER_ROW):
            val = 0
            for bit in range(16):
                x = word * 16 + bit
                p = px[x, y]
                is_on = (p < THRESHOLD) if ON_IS_BLACK else (p >= THRESHOLD)
                if is_on:
                    val |= (1 << (15 - bit))
            out.append((val >> 8) & 0xFF)
            out.append(val & 0xFF)
    assert len(out) == WORDS_PER_ROW * 2 * HEIGHT
    return out

def to_progmem_array(name, data):
    lines = [f"const uint8_t {name}[{len(data)}] PROGMEM = {{"]
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("  " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)

def main():
    header = ["// Auto-generated by convert_images.py — do not hand-edit.",
              "#pragma once",
              "#include <avr/pgmspace.h>",
              ""]
    for fname, varname in IMAGES:
        path = os.path.join(SOURCE_DIR, fname)
        data = convert(path)
        header.append(to_progmem_array(varname, data))
        header.append("")
    out_path = "/home/claude/nhd_poc/bitmaps.h"
    with open(out_path, "w") as f:
        f.write("\n".join(header))
    print(f"Wrote {out_path}")

if __name__ == "__main__":
    main()
