#!/usr/bin/env python3
"""Convert hp41_elite_font_table.json into a compile-time C table.

Sibling to gen_display_tables.py, but deliberately a separate script
rather than a mode of it: the Elite Mode font is a plain per-glyph
bitmap (3px wide x 5px tall), not the named-segment model the other
script's whole pipeline (SEGMENT_BIT_ORDER, per-segment pixel lists,
etc.) is built around - trying to force a bitmap font through that
machinery would be a worse fit than a small standalone script. Only the
low-level array-printing convention (checked-in JSON source of truth,
regenerable C, Doxygen-style header comments) is shared in spirit, not
in code.

Usage (run from font-tables/, or anywhere - paths below are relative to
this script's directory):
    python3 gen_elite_font_table.py > hp41_elite_font_table.c
"""
import json
import sys
from pathlib import Path
from typing import Any

JsonDict = dict[str, Any]

SCRIPT_DIR = Path(__file__).resolve().parent
ELITE_FONT_TABLE_PATH = SCRIPT_DIR / "hp41_elite_font_table.json"

ROWS_PER_GLYPH = 5
GLYPH_WIDTH_PX = 3
NUM_CODES = 128
PRINTABLE_ASCII_MIN = 32
PRINTABLE_ASCII_MAX = 127  # exclusive - matches Python range() convention


def check(condition: bool, message: str) -> None:
    """Power of 10 (Python adaptation), Rule 5 assertion helper.

    Never compiled out under `-O`/`-OO`, unlike a bare `assert` - see
    ../DEVIATIONS.md's implementation note (gen_display_tables.py uses
    the same helper for the same reason).
    """
    if not condition:
        raise AssertionError(message)


def _load_glyphs() -> JsonDict:
    """Read and parse hp41_elite_font_table.json's "glyphs" mapping."""
    with ELITE_FONT_TABLE_PATH.open() as f:
        data: JsonDict = json.load(f)
    glyphs: JsonDict = data["glyphs"]
    return glyphs


def _row_to_bits(row: str) -> int:
    """Pack one 3-character '0'/'1' row string into 3 bits (bit2=left, bit0=right).

    Args:
        row: Exactly 3 characters, each '0' or '1'.

    Returns:
        A 0-7 value with bit2 = row[0] (left pixel), bit1 = row[1]
        (center pixel), bit0 = row[2] (right pixel).
    """
    check(len(row) == GLYPH_WIDTH_PX, f"glyph row must be {GLYPH_WIDTH_PX} chars, got {row!r}")
    bits = 0
    for i, ch in enumerate(row):
        check(ch in ("0", "1"), f"glyph row char must be '0'/'1', got {row!r}")
        if ch == "1":
            bits |= 1 << (2 - i)
    return bits


def compute_table(glyphs: JsonDict) -> list[list[int]]:
    """Build a 128-entry table of 5-row bitmaps, zeroed (blank) for absent codes.

    Args:
        glyphs: Parsed "glyphs" mapping (string code -> 5 row strings).

    Returns:
        rows[code][r] for code in 0..127, r in 0..4 - a 0-7 packed row
        value, or 0 for every row of a code with no glyph defined
        (matches hp41_char_segments' convention of zeroing unpopulated
        codes rather than a fallback glyph).
    """
    table = [[0] * ROWS_PER_GLYPH for _ in range(NUM_CODES)]
    for code_str, rows in glyphs.items():
        code = int(code_str)
        check(0 <= code < NUM_CODES, f"glyph code {code} out of range")
        check(len(rows) == ROWS_PER_GLYPH,
              f"code {code}: expected {ROWS_PER_GLYPH} rows, got {len(rows)}")
        table[code] = [_row_to_bits(r) for r in rows]
    return table


def emit_c(table: list[list[int]], populated: list[int]) -> None:
    """Print hp41_elite_glyph_rows[128][5] as plain C.

    Args:
        table: computed by compute_table().
        populated: sorted list of codes that have a real glyph (for the
            stderr/comment summary, same style as gen_display_tables.py's
            blanked-code summary).
    """
    print("// Auto-generated by gen_elite_font_table.py from "
          "hp41_elite_font_table.json.")
    print("// Do not hand-edit - re-run the script instead.")
    print('#include "hp41_elite_font_table.h"')
    print()
    print(f"// {len(populated)} of {NUM_CODES} codes have a real glyph; "
          "every other code is all-zero (blank), matching which codes")
    print("// are already blank in the normal 14-segment font.")
    print(f"const uint8_t hp41_elite_glyph_rows[{NUM_CODES}][{ROWS_PER_GLYPH}] = {{")
    for code in range(NUM_CODES):
        row_str = ", ".join(str(v) for v in table[code])
        is_printable = PRINTABLE_ASCII_MIN <= code < PRINTABLE_ASCII_MAX
        comment = f"  // {code}" + (f" '{chr(code)}'" if is_printable else "")
        print(f"  {{{row_str}}},{comment}")
    print("};")

    print(f"// Populated codes: {populated}", file=sys.stderr)


def main() -> None:
    """Load the JSON source, compute the table, and print the generated C source."""
    glyphs = _load_glyphs()
    table = compute_table(glyphs)
    populated = sorted(int(c) for c in glyphs)
    emit_c(table, populated)


if __name__ == "__main__":
    main()
