#!/usr/bin/env python3
"""
Convert NUT0.ROM / NUT1.ROM / NUT2.ROM (confirmed format: big-endian
uint16_t, 4096 words/page, values 0-0x3FF) into a C source file exposing
them as flat uint16_t[4096] arrays, ready to point tabpage[] at.

Usage:
    python3 rom_to_c.py NUT0.ROM NUT1.ROM NUT2.ROM > rom_images.c
(run from wherever you copied the .ROM files, e.g. your soynut folder)
"""
import sys
import struct
import os

def convert(path):
    with open(path, "rb") as f:
        data = f.read()
    assert len(data) % 2 == 0, f"{path}: odd byte count"
    n = len(data) // 2
    words = struct.unpack(f">{n}H", data)  # big-endian, confirmed
    bad = [w for w in words if w > 0x3FF]
    if bad:
        print(f"// WARNING: {path} has {len(bad)} words > 0x3FF — "
              f"format assumption may not hold for this file", file=sys.stderr)
    return words

def c_name(path):
    base = os.path.splitext(os.path.basename(path))[0]
    return "rom_" + base.lower().replace("-", "_")

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    print("// Auto-generated by rom_to_c.py — do not hand-edit.")
    print("#include <stdint.h>")
    print()
    names = []
    for path in sys.argv[1:]:
        words = convert(path)
        name = c_name(path)
        names.append((path, name, len(words)))
        print(f"const uint16_t {name}[{len(words)}] = {{")
        for i in range(0, len(words), 16):
            chunk = words[i:i+16]
            print("  " + ", ".join(f"0x{w:03X}" for w in chunk) + ",")
        print("};")
        print()
    print("// Summary (for your reference, not compiled):")
    for path, name, count in names:
        print(f"//   {path} -> {name}[{count}]")

if __name__ == "__main__":
    main()
